In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0) 

In [9]:
df.shape

(5572, 3)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [17]:
X_train[:4]

550     Ok give me 5 minutes I think I see her. BTW yo...
4026                  &lt;#&gt;  in mca. But not conform.
5546           Ic. There are a lotta childporn cars then.
1795                     How much i gave to you. Morning.
Name: Message, dtype: object

In [18]:
type(y_train)

pandas.core.series.Series

In [19]:
y_train[:4]

550     0
4026    0
5546    0
1795    0
Name: spam, dtype: int64

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7691 sparse matrix of type '<class 'numpy.int64'>'
	with 59447 stored elements in Compressed Sparse Row format>

In [27]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
X_train_cv.shape

(4457, 7691)

In [32]:
 v.get_feature_names_out()[1000:1050]

array(['anyone', 'anyones', 'anyplaces', 'anythiing', 'anythin',
       'anything', 'anythingtomorrow', 'anytime', 'anyway', 'anyways',
       'anywhere', 'aom', 'apart', 'apartment', 'apes', 'apeshit',
       'aphex', 'apnt', 'apo', 'apologise', 'apologize', 'app',
       'apparently', 'appeal', 'appear', 'appendix', 'applausestore',
       'applebees', 'application', 'apply', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaches',
       'approaching', 'appropriate', 'approved', 'approx', 'apps', 'appt',
       'april', 'aproach', 'aptitude', 'aquarius', 'ar', 'arabian',
       'arcade', 'archive'], dtype=object)

In [40]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
np.where(X_train_np[0]!=0)

(array([ 908, 1539, 2133, 3157, 3312, 3424, 4399, 4489, 4643, 4892, 5546,
        5936, 6751, 6779, 6834, 7402, 7430, 7647], dtype=int64),)

In [43]:
X_train[:4][550]

"Ok give me 5 minutes I think I see her. BTW you're my alibi. You were cutting my hair the whole time."

In [48]:
X_train_np[0][5936]

1

In [51]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_cv, y_train)

MultinomialNB()

In [52]:
X_test_cv = v.transform(X_test)


In [54]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.97      0.93      0.95       135

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [55]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)

model.predict(emails_count)


array([0, 1], dtype=int64)

In [57]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])


In [58]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [60]:
y_pre = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.97      0.93      0.95       135

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

